version: "3.3"
services:
  auth:
    image: 'authdev:${TAG-latest}'
    container_name: auth-integrated
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=http://${DOMAIN?Variable not set}/auth
      - PORT=${PORT}
      # behind proxy
      - BASE_PATH=/auth
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority

    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not
        set}-auth-http.rule=PathPrefix(`/auth`)
      - traefik.http.services.${STACK_NAME?Variable not
        set}-auth.loadbalancer.server.port=${PORT}
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
