version: "3.3"
services:

  auth:
    image: 'authdev:${TAG-latest}'
    container_name: auth-integrated
    volumes:
      - .:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}/auth
      - PORT=${PORT}
      - BASE_PATH=/auth/
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-auth-http.rule=PathPrefix(`/auth`)
      - traefik.http.services.${STACK_NAME?Variable not set}-auth.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-auth-http.middlewares=auth-stripprefix
      - traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/auth

