version: "3.3"
services:
  auth:
    image: 'authdev:${TAG-latest}'
    container_name: auth-solo
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=http://${DOMAIN?Variable not set}:${SOLODEVPORT}
      - PORT
      - BASE_PATH=
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${SOLODEVPORT}:${PORT}"