version: "3.7"
services:
  auth:
    image: 'authdev'
    container_name: auth-solo
    volumes:
      - .:/app
    env_file:
      - .env.solo
      - .secrets
    environment:
      - PROTOCOL=http://
      - SERVER_NAME=${DOMAIN?Variable not set}:${SOLODEVPORT}
      - PORT
      - BASE_PATH=
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${SOLODEVPORT}:${PORT}"
    
  mongodb:
    image: bitnami/mongodb:latest
    container_name: auth-mongodb
    env_file:
      - .env.solo
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGODB_ROOT_USER -p $MONGODB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s